INSERT INTO restaurants (name, address_id)
VALUES
    ('Restaurant 1', NULL),
    ('Restaurant 2', NULL),
    ('Restaurant 3', NULL),
    ('Restaurant 4', NULL),
    ('Restaurant 5', NULL),
    ('Restaurant 6', NULL),
    ('Restaurant 7', NULL),
    ('Restaurant 8', NULL),
    ('Restaurant 9', NULL),
    ('Restaurant 10', NULL),
    ('Restaurant 11', NULL),
    ('Restaurant 12', NULL),
    ('Restaurant 13', NULL),
    ('Restaurant 14', NULL),
    ('Restaurant 15', NULL),
    ('Restaurant 16', NULL),
    ('Restaurant 17', NULL),
    ('Restaurant 18', NULL),
    ('Restaurant 19', NULL),
    ('Restaurant 20', NULL);

INSERT INTO users (first_name, last_name, email, role)
VALUES
    ('John', 'Doe', 'john.doe@example.com', 'user'),
    ('Jane', 'Smith', 'jane.smith@example.com', 'user'),
    ('Michael', 'Johnson', 'michael.johnson@example.com', 'user'),
    ('Emily', 'Brown', 'emily.brown@example.com', 'user'),
    ('William', 'Taylor', 'william.taylor@example.com', 'user'),
    ('Olivia', 'Miller', 'olivia.miller@example.com', 'user'),
    ('James', 'Anderson', 'james.anderson@example.com', 'user'),
    ('Sophia', 'Wilson', 'sophia.wilson@example.com', 'user'),
    ('Benjamin', 'Martinez', 'benjamin.martinez@example.com', 'user'),
    ('Isabella', 'Thompson', 'isabella.thompson@example.com', 'user'),
    ('Daniel', 'Harris', 'daniel.harris@example.com', 'user'),
    ('Mia', 'Clark', 'mia.clark@example.com', 'user'),
    ('Henry', 'Lewis', 'henry.lewis@example.com', 'user'),
    ('Charlotte', 'Young', 'charlotte.young@example.com', 'user'),
    ('Matthew', 'Lee', 'matthew.lee@example.com', 'user'),
    ('Ava', 'Walker', 'ava.walker@example.com', 'user'),
    ('David', 'Hall', 'david.hall@example.com', 'user'),
    ('Sofia', 'Allen', 'sofia.allen@example.com', 'user'),
    ('Joseph', 'Green', 'joseph.green@example.com', 'user'),
    ('Amelia', 'Baker', 'amelia.baker@example.com', 'user'),
    ('Alexander', 'Hill', 'alexander.hill@example.com', 'user'),
    ('Chloe', 'Turner', 'chloe.turner@example.com', 'user'),
    ('William', 'Adams', 'william.adams@example.com', 'user'),
    ('Ella', 'Morris', 'ella.morris@example.com', 'user'),
    ('James', 'Ward', 'james.ward@example.com', 'user'),
    ('Grace', 'Carter', 'grace.carter@example.com', 'user'),
    ('Liam', 'Phillips', 'liam.phillips@example.com', 'user'),
    ('Victoria', 'Ross', 'victoria.ross@example.com', 'user'),
    ('Daniel', 'White', 'daniel.white@example.com', 'user'),
    ('Avery', 'Watson', 'avery.watson@example.com', 'user'),
    ('Sebastian', 'Brooks', 'sebastian.brooks@example.com', 'user'),
    ('Scarlett', 'Wood', 'scarlett.wood@example.com', 'user'),
    ('Jackson', 'Cook', 'jackson.cook@example.com', 'user'),
    ('Abigail', 'Kelly', 'abigail.kelly@example.com', 'user'),
    ('Ethan', 'Sanders', 'ethan.sanders@example.com', 'user'),
    ('Harper', 'Price', 'harper.price@example.com', 'user'),
    ('Andrew', 'Simmons', 'andrew.simmons@example.com', 'user'),
    ('Madison', 'Perry', 'madison.perry@example.com', 'user'),
    ('Logan', 'Barnes', 'logan.barnes@example.com', 'user'),
    ('Lily', 'Rossi', 'lily.rossi@example.com', 'user'),
    ('Christopher', 'Lopez', 'christopher.lopez@example.com', 'user'),
    ('Samantha', 'Evans', 'samantha.evans@example.com', 'user'),
    ('Ryan', 'Morales', 'ryan.morales@example.com', 'user'),
    ('Evelyn', 'Gonzalez', 'evelyn.gonzalez@example.com', 'user'),
    ('Nathan', 'Hughes', 'nathan.hughes@example.com', 'user'),
    ('Aria', 'Foster', 'aria.foster@example.com', 'user'),
    ('Christian', 'Cooper', 'christian.cooper@example.com', 'user'),
    ('Mila', 'Richardson', 'mila.richardson@example.com', 'user'),
    ('Owen', 'Stewart', 'owen.stewart@example.com', 'user'),
    ('Avery', 'Mitchell', 'avery.mitchell@example.com', 'user');